using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace Zadanie
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Задание Большие гонки.На шоу Большие гонки собираются 4 команды из разных стран. В команде по 15 человек.Всего за одну игру команда проходит по 6 испытаний (6 разных игр). Будет неинтересно, если каждый раз игры будут одинаковыми, поэтому каждый раз игры разные. Главный организатор, Оливье Ганьян, добавляет новые игры. Необходимо правильно организовать классы, чтобы класс передачи «Большие Гонки» не изменял свой функционал, а добавлял новый. В консоли необходимо создать 4 команды: Россия, Франция, Китай и Казахстан, и чтобы они сыграли в 6 игр.");
            List<IGame> ru_strategies = new List<IGame>();
            List<Player> russian = new List<Player>();
            Organizator org = new Organizator("Оливье Ганьян");
            Player ru_player1 = new Player("Никта", Country.Россия);
            russian.Add(ru_player1);
            Player ru_player2 = new Player("Миша", Country.Россия);
            russian.Add(ru_player2);
            Player ru_player3 = new Player("Костя", Country.Россия);
            russian.Add(ru_player3);
            Player ru_player4 = new Player("Маша", Country.Россия);
            russian.Add(ru_player4);
            Player ru_player5 = new Player("Вика", Country.Россия);
            russian.Add(ru_player5);
            Player ru_player6 = new Player("Даша", Country.Россия);
            russian.Add(ru_player6);
            Player ru_player7 = new Player("Паша", Country.Россия);
            russian.Add(ru_player7);
            Player ru_player8 = new Player("Аня", Country.Россия);
            russian.Add(ru_player8);
            Player ru_player9 = new Player("Алиса", Country.Россия);
            russian.Add(ru_player9);
            Player ru_player10 = new Player("Сережа", Country.Россия);
            russian.Add(ru_player10);
            Player ru_player11 = new Player("Женя", Country.Россия);
            russian.Add(ru_player11);
            Player ru_player12 = new Player("Ангелина", Country.Россия);
            russian.Add(ru_player12);
            Player ru_player13 = new Player("Рита", Country.Россия);
            russian.Add(ru_player13);
            Player ru_player14 = new Player("Евсей", Country.Россия);
            russian.Add(ru_player14);
            Player ru_player15 = new Player("Ариша", Country.Россия);
            russian.Add(ru_player15);
            ru_strategies.Add(new BeachGame());
            ru_strategies.Add(new MouseTrapGame());
            ru_strategies.Add(new SeaGame());
            ru_strategies.Add(new FishingGame());
            ru_strategies.Add(new PostmanGame());
            ru_strategies.Add(new SlideGame());
            Team team_russian = new Team(russian, ru_strategies);
            List<Player> france = new List<Player>();
            List<IGame> frn_strategies = new List<IGame>();
            Player frc_player1 = new Player("Джейд", Country.Франция);
            france.Add(frc_player1);
            Player frc_player2 = new Player("Даниэль", Country.Франция);
            france.Add(frc_player2);
            Player frc_player3 = new Player("Жоржина", Country.Франция);
            france.Add(frc_player2);
            Player frc_player4 = new Player("Камиль", Country.Франция);
            france.Add(frc_player3);
            Player frc_player5 = new Player("Катрин", Country.Франция);
            france.Add(frc_player4);
            Player frc_player6 = new Player("Алис", Country.Франция);
            france.Add(frc_player5);
            Player frc_player7 = new Player("Лилу", Country.Франция);
            france.Add(frc_player7);
            Player frc_player8 = new Player("Манон", Country.Франция);
            france.Add(frc_player8);
            Player frc_player9 = new Player("Аделард", Country.Франция);
            france.Add(frc_player9);
            Player frc_player10 = new Player("Адриан", Country.Франция);
            france.Add(frc_player10);
            Player frc_player11 = new Player("Бернар", Country.Франция);
            france.Add(frc_player11);
            Player frc_player12 = new Player("Госс", Country.Франция);
            france.Add(frc_player12);
            Player frc_player13 = new Player("Джиннот", Country.Франция);
            france.Add(frc_player13);
            Player frc_player14 = new Player("Леонайд", Country.Франция);
            france.Add(frc_player14);
            Player frc_player15 = new Player("Жоас", Country.Франция);
            france.Add(frc_player15);
            frn_strategies.Add(new BeachGame());
            frn_strategies.Add(new MouseTrapGame());
            frn_strategies.Add(new SeaGame());
            frn_strategies.Add(new FishingGame());
            frn_strategies.Add(new PostmanGame());
            frn_strategies.Add(new SlideGame());
            Team team_france = new Team(france, frn_strategies);
            List<Player> china = new List<Player>();
            List<IGame> china_strategies = new List<IGame>();
            Player chn_player1 = new Player("Аи", Country.Китай);
            china.Add(chn_player1);
            Player chn_player2 = new Player("Бэй", Country.Китай);
            china.Add(chn_player2);
            Player chn_player3 = new Player("Вужоу", Country.Китай);
            china.Add(chn_player3);
            Player chn_player4 = new Player("Гонконг", Country.Китай);
            china.Add(chn_player4);
            Player chn_player5 = new Player("Дуий", Country.Китай);
            china.Add(chn_player5);
            Player chn_player6 = new Player("Ионглианг", Country.Китай);
            china.Add(chn_player6);
            Player chn_player7 = new Player("Йи", Country.Китай);
            china.Add(chn_player7);
            Player chn_player8 = new Player("Ксу", Country.Китай);
            china.Add(chn_player8);
            Player chn_player9 = new Player("Нианзу", Country.Китай);
            china.Add(chn_player9);
            Player chn_player10 = new Player("Киую", Country.Китай);
            china.Add(chn_player10);
            Player chn_player11 = new Player("Мейфен", Country.Китай);
            china.Add(chn_player11);
            Player chn_player12 = new Player("Нуо", Country.Китай);
            china.Add(chn_player12);
            Player chn_player13 = new Player("Сюли", Country.Китай);
            china.Add(chn_player13);
            Player chn_player14 = new Player("Хуиан", Country.Китай);
            china.Add(chn_player14);
            Player chn_player15 = new Player("Фу", Country.Китай);
            china.Add(chn_player15);
            china_strategies.Add(new BeachGame());
            china_strategies.Add(new MouseTrapGame());
            china_strategies.Add(new SeaGame());
            china_strategies.Add(new FishingGame());
            china_strategies.Add(new PostmanGame());
            china_strategies.Add(new SlideGame());
            Team team_china = new Team(china, china_strategies);
            List<Player> kazakhstan = new List<Player>();
            List<IGame> kzh_strategies = new List<IGame>();
            Player kzh_player1 = new Player("Айбар", Country.Казахстан);
            kazakhstan.Add(kzh_player1);
            Player kzh_player2 = new Player("Адиль", Country.Казахстан);
            kazakhstan.Add(kzh_player2);
            Player kzh_player3 = new Player("Ахмед", Country.Казахстан);
            kazakhstan.Add(kzh_player3);
            Player kzh_player4 = new Player("Гарифолла", Country.Казахстан);
            kazakhstan.Add(kzh_player4);
            Player kzh_player5 = new Player("Данияр", Country.Казахстан);
            kazakhstan.Add(kzh_player5);
            Player kzh_player6 = new Player("Жан", Country.Казахстан);
            kazakhstan.Add(kzh_player6);
            Player kzh_player7 = new Player("Казбек", Country.Казахстан);
            kazakhstan.Add(kzh_player7);
            Player kzh_player8 = new Player("Карим", Country.Казахстан);
            kazakhstan.Add(kzh_player8);
            Player kzh_player9 = new Player("Темирхан", Country.Казахстан);
            kazakhstan.Add(kzh_player9);
            Player kzh_player10 = new Player("Айнур", Country.Казахстан);
            kazakhstan.Add(kzh_player10);
            Player kzh_player11 = new Player("Бибинур", Country.Казахстан);
            kazakhstan.Add(kzh_player11);
            Player kzh_player12 = new Player("Гулзифа", Country.Казахстан);
            kazakhstan.Add(kzh_player12);
            Player kzh_player13 = new Player("Жайна", Country.Казахстан);
            kazakhstan.Add(kzh_player13);
            Player kzh_player14 = new Player("Зарина", Country.Казахстан);
            kazakhstan.Add(kzh_player14);
            Player kzh_player15 = new Player("Сара", Country.Казахстан);
            kazakhstan.Add(kzh_player15);
            kzh_strategies.Add(new BeachGame());
            kzh_strategies.Add(new MouseTrapGame());
            kzh_strategies.Add(new SeaGame());
            kzh_strategies.Add(new FishingGame());
            kzh_strategies.Add(new PostmanGame());
            kzh_strategies.Add(new SlideGame());
            Team team_kazah = new Team(kazakhstan, kzh_strategies);        
            IGame my_game = new GameDecorator(team_russian, new NewGame("Фиджитал-баскетбол"));
            Console.WriteLine("Игры для команды Россия:");
            my_game.Play();
            Console.WriteLine("Игры для команды Франция:");
            team_france.PlayGame();
            Console.WriteLine("Игры для команды Китая:");
            team_china.PlayGame();
            Console.WriteLine("Игры для команды Казахстана:");
            team_kazah.PlayGame();
            Console.ReadKey();
        }
    }
}
